### ISSUE TITLE
启用“增强模式”后Android System从应用列表消失，作用域无法选择它导致系统模块无效

### ISSUE THREAD

**Issue by Howard20181** [NekoInverter/EdXposedManagerR#13]
启用“增强模式”后Android System从应用列表消失，同时在作用域列表也消失了，无法选择它，导致系统模块无效

**Comment by NekoInverter** [comment]
启用增强之后 Android 系统会始终被添加到白名单

**Comment by Howard20181** [comment]
> 启用增强之后 Android 系统会始终被添加到白名单

作用域里面呢？也始终加入了？
