### ISSUE TITLE
最新版4.5.8.0为什么没有模块作用域选项

### ISSUE THREAD

**Issue by ssr123456789** [NekoInverter/EdXposedManagerR#15]
同上

**Comment by Howard20181** [comment]
必须使用0.5.1.3及以上版本的EdXposed才会出现选项

**Comment by ssr123456789** [comment]
> 必须使用0.5.1.3及以上版本的EdXposed才会出现选项

能给个最新版连接吗

**Comment by Howard20181** [comment]
> 能给个最新版连接吗

https://github.com/yujincheng08/EdXposed/actions
测试分支

**Comment by steven7851** [comment]
作用域已合并至canary 版本号0.5.0.6_4572
