### ISSUE TITLE
黑名单x失效啊

### ISSUE THREAD

**Issue by wzgrx** [NekoInverter/EdXposedManagerR#19]
能不能修复一下

**Comment by Howard20181** [comment]
> 能不能修复一下

这个大概和Manager 无关 
要EdXposed 那边修 
最新Canary 修复了一次黑名单

**Comment by wzgrx** [comment]
> > 能不能修复一下
> 
> 这个大概和Manager 无关
> 要EdXposed 那边修
> 最新Canary 修复了一次黑名单

好的，感谢开发者，另外想知道管理器下载插件只能调用第三方下载吗

**Comment by Howard20181** [comment]
> 好的，感谢开发者，另外想知道管理器下载插件只能调用第三方下载吗

这个管理器去除了应用内下载，必须用外部下载器

我不是开发者

**Comment by NekoInverter** [comment]
@yujincheng08

**Comment by yujincheng08** [comment]
昨天修过了。无log言屌。
